= Guidelines to Create Pull Request
:version:1.0.0-SNAPSHOT

== Introduction and Document Scope
Pull requests are modification requests in software development when a developer creates a unit of
change in the source code and requests that the modifications get incorporated into the "master"
source code and thus become part of the project.

The aim of the pull request as a code review process is to provide extra quality assurance means
to the software development ensuring that each and every change is reviewed at least by two persons.

The process handling pull requests is multi step workflow with several parties participating.
During the process the parties communicate, discuss different opinions, point out problems in
the code. Practice shows that this process leads many times interpersonal problems and human
conflicts.

This document gives technical and non-technical guidelines to follow in order to avoid human
conflicts and optimize the process aiming the highest possible efficiency.

=== Notes

These guidelines are mainly programming language agnostic. In case there is a guideline that is
language specific then it is denoted in the section title between parentheses, e.g. (Java).

The guidelines are independent of the tool that is used. However, the guidelines are expressed
in a way that assume the use of git and GitHub. This is because most of the application of the
guides will use this tool. Nevertheless the guides are general and can be adopted to other tools.
Basic knowledge and understanding of git is assumed.

=== Process Actors

There are at least two actors in the pull request process. One actor asking the pull and the
other one merging the change to the "master" source. There can be a third actor commenting the
pull request. This third actor is not necessarily a separate person, the actor accepting the
pull request may and usually does also act as commenting actor.

== Abbreviations

* PR - pull request
* YAGNI - You Aren't Gonna Need it (https://martinfowler.com/bliki/Yagni.html)

== Pull Request Guidelines

=== Scope

====
A single PR should focus on one single functional or non-functional change.
====

If there are multiple changes then they have to be developed in sepatare branches and their
incorporation into the main branch (usually `master`) should utilize multiple PRs.

It may happen that two changes share some common code change parts. In that case, there are
two different approaches:

. Order the changes and the first change contains the common part of the two changes. In this
case the second change depends on the first one. It is to use in case the changes alone are
not too big and creating a third PR would be a too big overhead. `F1` <- `F2`

. Create a change that contains only the common part that the other two changes depend on and the
separate changes depend only on this common change. In that case we have the `C` common change and the
two changes `C` <- `F1` && `C` <- `F2`, but the two changes `F1` and `F2` are independent of
each other. It is to use in case the changes are not trivial and splitting them into smaller
parts makes sense. It is also to use when the changes are complex and it cannot be foreseen
which change is going to be reviewed first. That way neither `F1` nor `F2` blocks the other change.

=== Code Cleanup

=== Import Optimization

=== Formatting Change